LeaRun.WebApp/Areas/SystemModule/Controllers/UploadController.cs
using LeaRun.Utilities;
using LeaRun.WebApp.Areas.SystemModule.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeaRun.WebApp.Areas.SystemModule.Controllers
{
    public class UploadController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ImageUpload(string id, string name,string type, string lastModifiedDate, int size, HttpPostedFileBase file)
        {
            string filePathName = string.Empty;
            var dirtory = Server.MapPath("~/Resource");
            string localPath = Path.Combine(dirtory, "pictures");
            if (Request.Files.Count == 0)
            {
                return Json(new { jsonrpc = 2.0, error = new { code = 102, message = "保存失败" }, id = "id" });
            }
            string ex = Path.GetExtension(file.FileName);
            if (!IsImageExtensionName(ex))
            {
                return Json(new { jsonrpc = 2.0, error = new { code = 500, message = "非图片文件" }, id = "id" });
            }
            filePathName = Guid.NewGuid().ToString("N") + ex;
            if (!System.IO.Directory.Exists(localPath))
            {
                System.IO.Directory.CreateDirectory(localPath);
            }
            var filePath = "/Resource/pictures/" + filePathName;
            file.SaveAs(Path.Combine(localPath, filePathName));
            return Json(new
            {
                jsonrpc = "2.0",
                id = id,
                filePath = filePath
            });
        }


        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return Content("没有文件！", "text/plain");
            }
            var fileName = Path.Combine(Request.MapPath("~/Upload"), Path.GetFileName(file.FileName));
            try
            {
                file.SaveAs(fileName);
                return Content("成功 ！", "text/plain");
            }
            catch
            {
                return Content("上传异常 ！", "text/plain");
            }
        }
        [HttpPost]
        public ActionResult UploadImage()
        {
            string savePath = "/Resource/UploadImages/";
            string saveUrl = "/Resource/UploadImages/";
            string fileTypes = "xlsx,zip,rar,ppt,doc,xls";
            int maxSize = 50000000;

            Hashtable hash = new Hashtable();

            HttpPostedFileBase file = Request.Files["imgFile"];
            if (file == null)
            {
                hash = new Hashtable();
                hash["error"] = 1;
                hash["message"] = "请选择文件";
                return Json(hash);
            }

            string dirPath = Server.MapPath(savePath);
            if (!Directory.Exists(dirPath))
            {
                hash = new Hashtable();
                hash["error"] = 1;
                hash["message"] = "上传目录不存在";
                return Json(hash);
            }

            string fileName = file.FileName;
            string fileExt = Path.GetExtension(fileName).ToLower();

            ArrayList fileTypeList = ArrayList.Adapter(fileTypes.Split(','));

            if (file.InputStream == null || file.InputStream.Length > maxSize)
            {
                hash = new Hashtable();
                hash["error"] = 1;
                hash["message"] = "上传文件大小超过限制";
                return Json(hash);
            }

            if (string.IsNullOrEmpty(fileExt) || Array.IndexOf(fileTypes.Split(','), fileExt.Substring(1).ToLower()) == -1)
            {
                hash = new Hashtable();
                hash["error"] = 1;
                hash["message"] = "上传文件扩展名是不允许的扩展名";
                return Json(hash);
            }

            string newFileName = DateTime.Now.ToString("yyyyMMddHHmmss_ffff", System.Globalization.DateTimeFormatInfo.InvariantInfo) + fileExt;
            string filePath = dirPath + newFileName;
            file.SaveAs(filePath);
            string fileUrl = saveUrl + newFileName;

            hash = new Hashtable();
            hash["error"] = 0;
            hash["url"] = fileUrl;

            return Json(hash, "text/html;charset=UTF-8"); ;

        }

        private bool IsImageExtensionName(string ex)
        {
            ex = ex.ToLower();
            if (ex == ".jpg" || ex == ".jpeg" || ex == ".png" || ex == ".bmp" || ex == ".gif")
                return true;
            else
                return false;
        }

    }
}

LeaRun.WebApp/Areas/Thirdparty/Controllers/UploadController.cs
using LeaRun.WebApp.Areas.SystemModule.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeaRun.WebApp.Areas.Thirdparty.Controllers
{
    public class UploadController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ImageUpload(string id, string name, string type, string lastModifiedDate, int size, HttpPostedFileBase file)
        {

            string filePathName = string.Empty;
            var dirtory = Server.MapPath("~/Resource");
            string localPath = Path.Combine(dirtory, "pictures");
            if (Request.Files.Count == 0)
            {
                return Json(new { jsonrpc = 2.0, error = new { code = 102, message = "保存失败" }, id = "id" });
            }
            string ex = Path.GetExtension(file.FileName);
            if (!IsImageExtensionName(ex))
            {
                return Json(new { jsonrpc = 2.0, error = new { code = 500, message = "非图片文件" }, id = "id" });
            }
            filePathName = Guid.NewGuid().ToString("N") + ex;
            if (!System.IO.Directory.Exists(localPath))
            {
                System.IO.Directory.CreateDirectory(localPath);
            }
            var filePath = "/Resource/pictures/" + filePathName;
            file.SaveAs(Path.Combine(localPath, filePathName));
            return Json(new
            {
                jsonrpc = "2.0",
                id = id,
                filePath = filePath
            });
        }


        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return Content("没有文件！", "text/plain");
            }
            var fileName = Path.Combine(Request.MapPath("~/Upload"), Path.GetFileName(file.FileName));
            try
            {
                file.SaveAs(fileName);
                return Content("成功 ！", "text/plain");
            }
            catch
            {
                return Content("上传异常 ！", "text/plain");
            }
        }
        [HttpPost]
        public ActionResult UploadImage()
        {
            string savePath = "/Resource/UploadImages/";
            string saveUrl = "/Resource/UploadImages/";
            string fileTypes = "xlsx,zip,rar,ppt,doc,xls";
            int maxSize = 50000000;

            Hashtable hash = new Hashtable();

            HttpPostedFileBase file = Request.Files["imgFile"];
            if (file == null)
            {
                hash = new Hashtable();
                hash["error"] = 1;
                hash["message"] = "请选择文件";
                return Json(hash);
            }

            string dirPath = Server.MapPath(savePath);
            if (!Directory.Exists(dirPath))
            {
                hash = new Hashtable();
                hash["error"] = 1;
                hash["message"] = "上传目录不存在";
                return Json(hash);
            }

            string fileName = file.FileName;
            string fileExt = Path.GetExtension(fileName).ToLower();

            ArrayList fileTypeList = ArrayList.Adapter(fileTypes.Split(','));

            if (file.InputStream == null || file.InputStream.Length > maxSize)
            {
                hash = new Hashtable();
                hash["error"] = 1;
                hash["message"] = "上传文件大小超过限制";
                return Json(hash);
            }

            if (string.IsNullOrEmpty(fileExt) || Array.IndexOf(fileTypes.Split(','), fileExt.Substring(1).ToLower()) == -1)
            {
                hash = new Hashtable();
                hash["error"] = 1;
                hash["message"] = "上传文件扩展名是不允许的扩展名";
                return Json(hash);
            }

            string newFileName = DateTime.Now.ToString("yyyyMMddHHmmss_ffff", System.Globalization.DateTimeFormatInfo.InvariantInfo) + fileExt;
            string filePath = dirPath + newFileName;
            file.SaveAs(filePath);
            string fileUrl = saveUrl + newFileName;

            hash = new Hashtable();
            hash["error"] = 0;
            hash["url"] = fileUrl;

            return Json(hash, "text/html;charset=UTF-8"); ;

        }

        private bool IsImageExtensionName(string ex)
        {
            ex = ex.ToLower();
            if (ex == ".jpg" || ex == ".jpeg" || ex == ".png" || ex == ".bmp" || ex == ".gif")
                return true;
            else
                return false;
        }

    }
}

LeaRun.WebApp/Areas/SystemModule/Views/Upload/ImageList.cshtml
@model LbangCMS.Areas.Admin.Models.ImageLisModel
@{
    ViewBag.Title = "PictureList";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section head{
    <link href="~/Areas/Admin/Content/libs/zui/lib/datatable/zui.datatable.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/libs/laypage/skin/laypage.css" rel="stylesheet" />
}
@section nav{
    <li><a href="#">素材管理</a></li>
    <li class="active">图片管理</li>
}

@section script{
    <script src="~/Areas/Admin/Content/libs/zui/lib/datatable/zui.datatable.js"></script>
    <script src="~/Areas/Admin/Content/libs/laypage/laypage.js"></script>
<script src="~/Areas/Admin/Content/libs/clipboard/clipboard.min.js"></script>
    <script type="text/javascript">
        function to_datatable() {
            $('table.datatable').datatable({
                checkable: false,
                checkByClickRow: false,
                fixedHeader: false
            });
        }
        function setPager() {
            laypage({
                cont: 'pager',
                pages: $("#TotalPage").val(), //可以叫服务端把总页数放在某一个隐藏域，再获取。假设我们获取到的是18
                curr: $("#CurentPageIndex").val(),
                jump: function (e, first) { //触发分页后的回调
                    if (!first) { //一定要加此判断，否则初始时会无限刷新
                        reload_data(e.curr);
                    }
                }
            });
        }
        function reload_data(pageIndex) {
            var url = '@Url.Action("ImageList", "Upload")' + "?PageIndex=" + pageIndex + "&r=" + Math.random();
            $.get(url, function (data) {
                $("#view").html(data);
                to_datatable()
                setPager();
            })
        }
        function remove_item(id) {
            layer.confirm('确定要删除吗?', { icon: 3, title: '提示' }, function (index) {
                var url = '@Url.Action("RemovePicture", "Upload")';
                $.post(url, { id: id }, function (data) {
                    layer.msg("删除成功", { time: 800 });
                    reload_data($("#currentPageIndex").val());

                })
            });
        }
        function uploadImg()
        {
            layer.open({
                type: 2,
                title: "上传图片",
                content: '@Url.Action("Upload", "Upload")',
                area: ['700px', '500px']
            });
        }
        $().ready(function () {
            to_datatable()
            setPager();
            var clipboard = new Clipboard('.btnCopy');
            clipboard.on('success', function (e) {
                layer.msg("复制成功", {time:1000})
            });

            clipboard.on('error', function (e) {
                layer.msg("复制失败", { time: 1000 })
            });
        });
    </script>
    }

<div class="panel">
    <div class="panel-heading">
        <button class="btn btn-primary" id="btnAdd" type="button" onclick="uploadImg()">上传图片</button>
    </div>
    <div class="panel-body">
        <div id="view">
            @{Html.RenderPartial("_ImageListPartial", Model);}

        </div>
        <div class="text-center" id="pager"></div>
    </div>
</div>

LeaRun.WebApp/Areas/SystemModule/Views/Upload/Index.cshtml
@{
    ViewBag.Title = "图片上传";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}
<link href="~/Content/Scripts/webuploader/webuploader.css" rel="stylesheet" />
<link href="~/Content/Styles/pictureupload.css" rel="stylesheet" />
<script src="~/Content/Scripts/webuploader/webuploader.js"></script>
<script src="~/Content/Scripts/pictureupload.js"></script>
<div class="page-container">

    <div id="uploader" class="wu-example">
        <div class="queueList">
            <div id="dndArea" class="placeholder">
                <div id="filePicker"></div>
                <p>或将图片拖到这里，单次最多可选100张,单张不能大于2M,总共不能大于100M</p>
            </div>
        </div>
        <div class="statusBar" style="display:none;">
            <div class="progress">
                <span class="text">0%</span>
                <span class="percentage"></span>
            </div><div class="info"></div>
            <div class="btns">
                <div id="filePicker2"></div><div class="uploadBtn">开始上传</div>
            </div>
        </div>
    </div>

</div>

LeaRun.WebApp/Areas/SystemModule/Views/Upload/Upload.cshtml
@{
    ViewBag.Title = "图片上传";
    Layout = "~/Views/Shared/_LayoutForm.cshtml";
}
<link href="~/Content/Scripts/webuploader/webuploader.css" rel="stylesheet" />
<link href="~/Content/Styles/pictureupload.css" rel="stylesheet" />
<script src="~/Content/Scripts/webuploader/webuploader.js"></script>
<script src="~/Content/Scripts/pictureupload.js"></script>


<div class="page-container">

    <div id="uploader" class="wu-example">
        <div class="queueList">
            <div id="dndArea" class="placeholder">
                <div id="filePicker"></div>
                <p>或将图片拖到这里，单次最多可选100张,单张不能大于2M,总共不能大于100M</p>
            </div>
        </div>
        <div class="statusBar" style="display:none;">
            <div class="progress">
                <span class="text">0%</span>
                <span class="percentage"></span>
            </div><div class="info"></div>
            <div class="btns">
                <div id="filePicker2"></div><div class="uploadBtn">开始上传</div>
            </div>
        </div>
    </div>

</div>

LeaRun.WebApp/Areas/SystemModule/Views/Upload/_ImageListPartial.cshtml
@model LbangCMS.Areas.Admin.Models.ImageLisModel
<input type="hidden" id="CurentPageIndex" value="@Model.CurrentPageIndex" />
<input type="hidden" id="TotalPage" value="@Model.TotalPage" />

<section class="cards">
    @if (Model != null && Model.PictureList != null)
    {
        foreach (var item in Model.PictureList)
        {
            <div class="col-md-2">
                <div class="card">
                    @Html.Img(item.FilePath)
                    <a href="#" class="card-heading"><strong>@item.FileName</strong></a>
                    <div class="card-actions">
                        @{ var imageUrl = System.Configuration.ConfigurationManager.AppSettings["ImageDomain"] + item.FilePath;}
                        <button class="btn btn-primary btnCopy" data-clipboard-text="@imageUrl"><i class="icon-copy"></i> 复制地址</button>
                        <button class="btn btn-warning" onclick="remove_item(@item.Id)"><i class="icon-times"></i> 删除</button>
                    </div>
                </div>
            </div>
                                }

                            }

</section>
@if (Model.PictureList == null || !Model.PictureList.Any())
{
    <div class="alert alert-info">暂无图片信息</div>
}